"""Create freebies table

Revision ID: 9223ee4121cb
Revises: aef5ef5809a8
Create Date: 2025-06-05 04:42:48.554450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9223ee4121cb'
down_revision = 'aef5ef5809a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('founding_year',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('devs', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('freebies', schema=None) as batch_op:
        batch_op.alter_column('dev_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freebies', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('dev_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('devs', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('founding_year',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
