"""Create freebies table

Revision ID: aef5ef5809a8
Revises: 5f72c58bf48c
Create Date: 2025-06-05 04:38:33.446196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aef5ef5809a8'
down_revision = '5f72c58bf48c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
    'freebies',
    sa.Column('id', sa.Integer(), primary_key=True),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('dev_id', sa.Integer(), sa.ForeignKey('devs.id')),
    sa.Column('company_id', sa.Integer(), sa.ForeignKey('companies.id'))
)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
